# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-12-06 09:49
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Ask_buk', '0002_auto_20161206_0924'),
    ]

    operations = [
        migrations.AddField(
            model_name='like_answer',
            name='is_like',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='like_question',
            name='is_like',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterUniqueTogether(
            name='like_answer',
            unique_together=set([('user', 'answer')]),
        ),
        migrations.AlterUniqueTogether(
            name='like_question',
            unique_together=set([('user', 'question')]),
        ),
    ]
